<?php

 /*********************************************************************************
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/eapm/webex/language/fr_FR.lang.php,  Tue 20/12/11 15:23:18 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Traduction par CARRENET
  *   www.carrenet.com - info@carrenet.com
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'url' => 'URL' );

?>
