<?php

 /*********************************************************************************
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/SNIP/language/fr_FR.lang.php,  Tue 20/12/11 15:23:18 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Traduction par CARRENET
  *   www.carrenet.com - info@carrenet.com
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$mod_strings = array ( 
   'LBL_SNIP_SUMMARY' => 'L&#039;archivage email est un service d&#039;import automatique qui autorise les utilisateurs à importer les emails dans Sugar en leur envoyant depuis n&#039;importe quel client ou service vers un eamil fourni par Sugar. Chaque instance de Sugar possède sa propre adresse email. Pour importer les emails, un utilisateur les envoie à l&#039;email fourni en utilisant les champs POUR, CC ou BCC. Le service importera les emails dans l&#039;instance Sugar.  Le service importe l&#039;email, ainsi que toutes les pièces jointes, images et événements de calendrier, et créer des enregistrements associés avec des enregistrements existant en se basant sur la correspondance des adresses email.
    <br><br>Exemple : En tant qu&#039;utilisateur, quand je consulte un Compte, je serais capable de voir tous les emails associé au Compte basé sur l&#039;adresse email inscrite dans le Compte. Je serais aussi capable de voir les emails associés aux Contacts qui sont liés au Compte.
    <br><br>Acceptez les termes ci-dessous et cliquez sur Activer pour commencer à utiliser le service. Vous pourrez désactiver le service n&#039;importe quand. Une fois le service activé, l&#039;adresse email utilisée pour le service s&#039;affichera.
    <br><br>' ,
   'LBL_REGISTER_SNIP_FAIL' => 'Echec du contact du service d&#039;archivage email : %s!<br>' ,
   'LBL_CONFIGURE_SNIP' => 'Archivage email' ,
   'LBL_DISABLE_SNIP' => 'Désactiver' ,
   'LBL_SNIP_APPLICATION_UNIQUE_KEY' => 'Clef unique de l&#039;application' ,
   'LBL_SNIP_USER' => 'Utilisateur archivage email' ,
   'LBL_SNIP_PWD' => 'Mot de passe archivage email' ,
   'LBL_SNIP_SUGAR_URL' => 'Url de l&#039;instance de ce Sugar' ,
   'LBL_SNIP_CALLBACK_URL' => 'URL du service d&#039;archivage email' ,
   'LBL_SNIP_USER_DESC' => 'Utilisateur archivage email' ,
   'LBL_SNIP_STATUS_OK' => 'Activé' ,
   'LBL_SNIP_STATUS_OK_SUMMARY' => 'Cette instance Sugar a été connecté avec succès au serveur d&#039;archivage email.' ,
   'LBL_SNIP_STATUS_ERROR' => 'Erreur' ,
   'LBL_SNIP_STATUS_ERROR_SUMMARY' => 'L&#039;instance possède une licence valide pour le serveur d&#039;archivage email, mais le serveur retourne l&#039;erreur suivante:' ,
   'LBL_SNIP_STATUS_FAIL' => 'Ne peut être enrgistré avec le serveur d&#039;archivage email' ,
   'LBL_SNIP_STATUS_FAIL_SUMMARY' => 'Le service d&#039;archivage email est actuellement indisponible. Soit le service est en panne, soit la connexion vers l&#039;instance Sugar a échoué.' ,
   'LBL_SNIP_GENERIC_ERROR' => 'Le service d&#039;archivage email est actuellement indisponible. Soit le service est en panne, soit la connexion vers l&#039;instance Sugar a échoué.' ,
   'LBL_SNIP_STATUS_RESET' => 'N&#039;est pas encore lancé' ,
   'LBL_SNIP_STATUS_PROBLEM' => 'Problème: %s' ,
   'LBL_SNIP_NEVER' => ' Jamais' ,
   'LBL_SNIP_STATUS_SUMMARY' => 'Staut du service d&#039;archivage email:' ,
   'LBL_SNIP_ACCOUNT' => 'Compte' ,
   'LBL_SNIP_STATUS' => 'Statut' ,
   'LBL_SNIP_LAST_SUCCESS' => 'Dernier lancement réussi' ,
   'LBL_SNIP_DESCRIPTION' => 'Le service d&#039;archivage email est un système d&#039;archivage automatique d&#039;email' ,
   'LBL_SNIP_DESCRIPTION_SUMMARY' => 'Cela vous autorise à voir les emails envoyés ou reçus de vos contacts dans SugarCRM, sans avoir à importer manuellement et relier les e-mails.' ,
   'LBL_SNIP_PURCHASE_SUMMARY' => 'Pour utiliser l&#039;archivage email, vous devez acheter une licence pour votre instance SugarCRM' ,
   'LBL_SNIP_PURCHASE' => 'Cliquez ici pour acheter' ,
   'LBL_SNIP_EMAIL' => 'Addresse d&#039;archivage email' ,
   'LBL_SNIP_AGREE' => 'J&#039;accepte les termes ci-dessus et <a href=&#034;http://www.sugarcrm.com/crm/TRUSTe/privacy.html&#034; target=&#034;_blank&#034;>l&#039;accord de confidentialité</a>.' ,
   'LBL_SNIP_PRIVACY' => 'privacy agreement' ,
   'LBL_SNIP_STATUS_PINGBACK_FAIL' => 'Pingback échoué' ,
   'LBL_SNIP_STATUS_PINGBACK_FAIL_SUMMARY' => 'Le serveur d&#039;archivage email est incapable d&#039;établir une connexion avec Sugar. Veuillez essayer à nouveau ou  <a href=&#034;http://www.sugarcrm.com/crm/case-tracker/submit.html?lsd=supportportal&amp;tmpl=&#034; target=&#034;_blank&#034;>contacter le support client</a>.' ,
   'LBL_SNIP_BUTTON_ENABLE' => 'Activer l&#039;archivage email' ,
   'LBL_SNIP_BUTTON_DISABLE' => 'Désactiver l&#039;archivage email' ,
   'LBL_SNIP_BUTTON_RETRY' => 'Nouvelle tentative de connexion' ,
   'LBL_SNIP_ERROR_DISABLING' => 'Une erreur s&#039;est produite tout en essayant de communiquer avec le serveur d&#039;archivage email, et le service ne peut pas être désactivé.' ,
   'LBL_SNIP_ERROR_ENABLING' => 'Une erreur s&#039;est produite tout en essayant de communiquer avec le serveur d&#039;archivage email, et le service ne peut pas être activé.' ,
   'LBL_CONTACT_SUPPORT' => 'Veuillez essayer à nouveau ou contactez le Support de SugarCRM.' ,
   'LBL_SNIP_SUPPORT' => 'Veuillez contactez le Support de SugarCRM pour assistance.' ,
   'ERROR_BAD_RESULT' => 'Résultat incorrect retourné par le service' ,
   'ERROR_NO_CURL' => 'Les extensions cURL sont obligatoires, mais n&#039;ont pas été activées' ,
   'ERROR_REQUEST_FAILED' => 'Ne peut pas contacter le serveur' ,
   'LBL_CANCEL_BUTTON_TITLE' => 'Annuler' ,
   'LBL_SNIP_MOUSEOVER_STATUS' => 'Ceci est le statut du service d&#039;archivage email sur votre instance. Le statut indique si la connexion entre le serveur d&#039;archivage email et de votre Sugar est un succès.' ,
   'LBL_SNIP_MOUSEOVER_EMAIL' => 'Ceci est l&#039;adresse email de l&#039;archivage d&#039;email à utiliser pour importer les emails dans Sugar.' ,
   'LBL_SNIP_MOUSEOVER_SERVICE_URL' => 'Ceci est l&#039;URL du serveur d&#039;archivage email. Toutes les requêtes, comme activer ou désactiver le service, seront relayés par cette URL.' ,
   'LBL_SNIP_MOUSEOVER_INSTANCE_URL' => 'Ceci est l&#039;URL des webservices de votre Sugar. Le serveur d&#039;archivage email se connectera à votre serveur par cette URL.' );

?>
