<?php

 /*********************************************************************************
  /*********************************************************************************
  * File generated by the Sugar Translation Suite (Contributor : www.grupa-atlantis.pl)
  *********************************************************************************/
  /*********************************************************************************
  * $Header: modules/Connectors/connectors/sources/ext/eapm/facebook/language/fr_FR.lang.php,  Tue 20/12/11 15:23:18 
  * Description : .
  * Portions created by SugarCRM are Copyright (C) SugarCRM, Inc. All Rights Reserved.
  * Traduction par CARRENET
  *   www.carrenet.com - info@carrenet.com
  *********************************************************************************/

if(!defined('sugarEntry') || !sugarEntry) die('Not A Valid Entry Point');

$connector_strings = array ( 
   'LBL_LICENSING_INFO' => '<table border=&#034;0&#034; cellspacing=&#034;1&#034;><tr><td valign=&#034;top&#034; width=&#034;35%&#034; class=&#034;dataLabel&#034;>Les &#034;Clé API&#034; et &#034;Code secret API&#034; sont les paramètres que vous obtenez depuis Facebook&#169; lorsque vous créez une nouvelle application. Pour commencer, allez sur : <a href=\&#039;http://www.facebook.com/developers/createapp.php\&#039;>http://www.facebook.com/developers/createapp.php</a>.<br><ol><li>Saisir le nom de votre appplication, il s&#39;agit du nom que l&#39;utilisateur verra apparaitre lorsqu&#39;il s&#39;authentifira depuis SugarCRM</li><li>Cliquer sur Site Web et saisir l&#39;URL de votre instance SugarCRM dans &#034;Site URL&#034;</li><li>Sauvegarder les modificatioins</li><li>Copier les &#034;Clé API&#034; et &#034;Code secret API&#034; dans les champs correspondants dans les paramètrers de connexions</li></ol></td></tr></table>' ,
   'oauth_consumer_key' => 'API Key' ,
   'oauth_consumer_secret' => 'App confidentiel' );

?>
